### PR TITLE
Fix bug with resolving relative symlinks during linux header detection

### LINKED ISSUE #2037: Upstream kernel header packages with relative symlinks always fall back to Pixie prepackaged headers
**Describe the bug**
Pixie requires linux kernel headers since BCC is used to compile our eBPF programs. These headers can either be supplied by installing the distro provided linux headers package or installed by pixie through our [prepackaged linux headers](https://github.com/pixie-io/pixie/blob/3c41d554215528e688328aef94192e696db617dc/bazel/linux_headers.bzl#L29).

When working with @feynmanliang, we realized that installing an openSUSE MicroOS linux headers package results in Pixie falling back to our prepackaged headers. While this should in theory result in equivalent behavior, the upstream distro's headers are preferred since they are more likely to be what the given kernel expects.

The openSUSE linux headers use a relative symlink and Pixie's logic to locate the headers fails for this case:

```
# File layout seen after installing openSUSE headers
# ls -alh  /lib/modules/6.11.0-1-default/
total 43M
drwxr-xr-x. 1 root root  674 Oct  2 18:10 .
drwxr-xr-x. 1 root root   32 Sep 28 00:36 ..
-rw-r--r--. 1 root root   65 Sep 25 05:56 .vmlinuz.hmac
-rw-r--r--. 1 root root 7.6M Sep 25 05:56 System.map
lrwxrwxrwx. 1 root root   46 Sep 25 05:56 build -> ../../../src/linux-6.11.0-1-obj/x86_64/default

# PEM logs that show installed headers are misdetected as missing
I20241002 18:32:19.083017 22431 kernel_version.cc:82] Obtained Linux version string from `uname`: 6.11.0-1-default
I20241002 18:32:19.083026 22431 linux_headers.cc:381] Detected kernel release (uname -r): 6.11.0-1-default
I20241002 18:32:19.083271 22431 linux_headers.cc:396] Not Found : Could not find 'source' or 'build' under /lib/modules/6.11.0-1-default.
I20241002 18:32:19.083294 22431 linux_headers.cc:244] Looking for host Linux headers at /host/lib/modules/6.11.0-1-default/build.
I20241002 18:32:19.083403 22431 linux_headers.cc:399] Not Found : Did not find host headers at resolved path: /host/../../../src/linux-6.11.0-1-obj/arm64/default.
I20241002 18:32:19.083415 22431 linux_headers.cc:342] Attempting to install packaged headers.
```

This is in contrast to Ubuntu's header package, which uses an absolute symlink:
```
$ ls -alh /lib/modules/$(uname -r) | grep build
lrwxrwxrwx  1 root root   37 Aug  8 21:15 build -> /usr/src/linux-headers-6.8.0-1013-gcp
```

**To Reproduce**
1. Using a Ubuntu instance, install the `linux-headers-$(uname -r)` package
2. Run `stirling_wrapper` and see that Pixie locates the headers properly
3. Replace `/lib/modules/$(uname -r)/build` with an openSUSE style, relative symlink
```
$ cd /lib/modules/$(uname -r)
$ sudo ln -s ../../../../usr/src/linux-headers-$(uname -r) build
```
4. See that `stirling_wrapper` falls back to prepackaged headers.

**Expected behavior**
Upstream installed linux headers should be correctly identified.

**App information (please complete the following information):**
- Pixie version: v0.14.11
- Node Kernel version: 6.11
- Distro: openSUSE MicroOS
- K8s cluster version: N/A

### PR DESCRIPTION
**Pull request by ddelnano**
Summary: Fix bug with resolving relative symlinks during linux header detection

Please see linked issue for details

Relevant Issues: Closes #2037

Type of change: /kind bugfix

Test Plan: Verified the following
- [x] Confirmed with user that reported the issue that this works for openSUSE's MicroOS linux headers
- [x] Verified on Ubuntu that using an absolute symlink works (upstream package, no modification)
```
ddelnano@dev-vm:/lib/modules/6.8.0-1015-gcp$ ls -l build
lrwxrwxrwx 1 root root 37 Sep  2 14:42 build -> /usr/src/linux-headers-6.8.0-1015-gcp

# Verify custom built stirling_wrapper identifies absolute headers
$ sudo docker run -v /:/host -v /sys:/sys -v /var/lib/docker:/var/lib/docker --pid=host --cgroupns host --env "PL_HOST_PATH=/host"  bazel/src/stirling/binaries:stirling_wrapper_image

I20241011 21:32:38.893605 395713 linux_headers.cc:257] Looking for host Linux headers at /host/lib/modules/6.8.0-1015-gcp/build.
I20241011 21:32:38.893646 395713 linux_headers.cc:237] Symlink target is an absolute path. Converting that to host path: /usr/src/linux-headers-6.8.0-1015-gcp -> /host/usr/src/linux-headers-6.8.0-1015-gcp.
I20241011 21:32:38.893750 395713 linux_headers.cc:261] Linked host headers at /host/usr/src/linux-headers-6.8.0-1015-gcp to symlink in pem namespace at /lib/modules/6.8.0-1015-gcp/build.
I20241011 21:32:38.893783 395713 linux_headers.cc:257] Looking for host Linux headers at /host/lib/modules/6.8.0-1015-gcp/source.
```
- [x] Verified on Ubuntu that using a relative symlink (modified by hand with reproduction steps in #2037)
```
# Verify build is a relative symlink and resolves outside a container
ddelnano@dev-vm:/lib/modules/6.8.0-1015-gcp$ ls -l
total 1480
lrwxrwxrwx  1 root root     48 Oct 11 20:39 build -> ../../../../usr/src/linux-headers-6.8.0-1015-gcp

# Verify custom built stirling_wrapper identifies relative headers
$ sudo docker run -v /:/host -v /sys:/sys -v /var/lib/docker:/var/lib/docker --pid=host --cgroupns host --env "PL_HOST_PATH=/host"  bazel/src/stirling/binaries:stirling_wrapper_image

I20241011 21:30:16.825937 395471 linux_headers.cc:257] Looking for host Linux headers at /host/lib/modules/6.8.0-1015-gcp/build.
I20241011 21:30:16.825973 395471 linux_headers.cc:242] Symlink target is a relative path. Concatenating it to parent directory: /host/lib/modules/6.8.0-1015-gcp/../../../../usr/src/linux-headers-6.8.0-1015-gcp
I20241011 21:30:16.826067 395471 linux_headers.cc:261] Linked host headers at /host/lib/modules/6.8.0-1015-gcp/../../../../usr/src/linux-headers-6.8.0-1015-gcp to symlink in pem namespace at /lib/modules/6.8.0-1015-gcp/build.
```

Changelog Message: Fixed an issue where certain linux upstream distro's header packages would fail to be identified

### CODE REVIEW

**Comment by feynmanliang** [comment]
Thank you!

File: src/stirling/utils/linux_headers.cc [hunk 1]
```diff
@@ -229,7 +229,23 @@ StatusOr<std::filesystem::path> ResolvePossibleSymlinkToHostPath(const std::file
...
+    if (resolved.is_absolute()) {
+      const auto host_path_from_abs_symlink = system::Config::GetInstance().ToHostPath(resolved);
+      LOG(INFO) << absl::Substitute(
+          "Symlink is using absolute path. Converting that to host path: $0 -> $1.",
+          resolved.string(), host_path_from_abs_symlink.string());
+      return host_path_from_abs_symlink;
+    }
+    LOG(INFO) << absl::Substitute(
+        "Symlink is using relative path, using link name directly instead: $0", p.string());
+    return p;
```
Comment (oazizi000) [inline src/stirling/utils/linux_headers.cc:247]: Summarizing in person discussion: We should try to return the input path (with it's host prefix) + the relative path in this case. Rationale is that the function is supposed to be resolving the symlink, so we should be doing it in this case too for consistency.

File: src/stirling/utils/linux_headers.cc [hunk 2]
```diff
@@ -229,7 +229,23 @@ StatusOr<std::filesystem::path> ResolvePossibleSymlinkToHostPath(const std::file
     return error::Internal(ec.message());
   }
 
-  const auto resolved_host_path = system::Config::GetInstance().ToHostPath(resolved);
+  // Relative symlinks can form an invalid path when converted to a host path when there are too
+  // many "../" references, causing the mounted host path to be lost.
+  // This happens for openSUSE's linux-header package. In order to handle
+  // this, we only use the symlink target if it is an absolute path and fall back to using the
+  // symlink name directly when it's relative path (/host/lib/modules/<uname>/build).
+  const std::filesystem::path resolved_host_path = [&resolved, &p]() -> std::filesystem::path {
```
Comment (JamesMBartlett) [inline src/stirling/utils/linux_headers.cc:237]: What is the purpose of the lambda here?

Comment (ddelnano) [reply src/stirling/utils/linux_headers.cc:237]: I was trying to keep the variable `const` despite the additional branching. I'll remove it in favor of a more simple if/else check.

File: src/stirling/utils/linux_headers.cc (hunk 1 above)
Comment (ddelnano) [reply src/stirling/utils/linux_headers.cc]: This has been addressed in 0322c23b85bcb270c6bf7259f27999fdaaff5999

File: src/stirling/utils/linux_headers.cc (hunk 2 above)
Comment (ddelnano) [reply src/stirling/utils/linux_headers.cc]: Updated in 0322c23b85bcb270c6bf7259f27999fdaaff5999

File: src/stirling/utils/linux_headers.cc [hunk 3]
```diff
@@ -229,7 +229,20 @@ StatusOr<std::filesystem::path> ResolvePossibleSymlinkToHostPath(const std::file
...
+    resolved_host_path = system::Config::GetInstance().ToHostPath(resolved);
+    LOG(INFO) << absl::Substitute(
+        "Symlink target is an absolute path. Converting that to host path: $0 -> $1.",
+        resolved.string(), resolved_host_path.string());
+  } else {
+    resolved_host_path /= resolved.string();
+    LOG(INFO) << absl::Substitute(
+        "Symlink target is a relative path. Concatenating it to parent directory: $0",
+        resolved_host_path.string());
+  }
```
Comment (oazizi000) [inline src/stirling/utils/linux_headers.cc:245]: Maybe convert the LOGs to VLOGs (or remove them).

File: src/stirling/utils/linux_headers.cc [hunk 4]
```diff
@@ -229,7 +229,20 @@ StatusOr<std::filesystem::path> ResolvePossibleSymlinkToHostPath(const std::file
     return error::Internal(ec.message());
   }
 
-  const auto resolved_host_path = system::Config::GetInstance().ToHostPath(resolved);
+  // Relative paths containing "../" can result in an invalid host mount path when using
+  // ToHostPath. Therefore, we need to treat the absolute and relative cases differently.
+  std::filesystem::path resolved_host_path = p.parent_path();
```
Comment (oazizi000) [inline src/stirling/utils/linux_headers.cc:234]: You can probably push the `p.parent_path()` into the else clause since that's the only branch it's relevant for.

**Review by oazizi000 — APPROVED** [review]

File: src/stirling/utils/linux_headers.cc (hunk 3 above)
Comment (ddelnano) [reply src/stirling/utils/linux_headers.cc]: Fixed in ed7b839d630c0ee2acdde1319a008d6d099e0e18

File: src/stirling/utils/linux_headers.cc (hunk 4 above)
Comment (ddelnano) [reply src/stirling/utils/linux_headers.cc]: Updated in ed7b839d630c0ee2acdde1319a008d6d099e0e18
