### PR TITLE
[bpf tests] Remove timing dependence from dynamic_bpftrace_connector_bpf_test

### LINKED ISSUE #1245: `dynamic_bpftrace_connector_bpf_test` shouldn't be timing dependent.
**Describe the Task**
The `dynamic_bpftrace_connector_bpf_test` currently sleeps for 1 second and then makes assertions. However, because QEMU executes things more slowly this fails. Instead the test should check for the records it expects in a loop, rather than relying on a sleep.
Additionally, the test makes assertions about how recently an event was received. Instead of doing this it should either not make assertions about the timestamp or do the assertion in a more robust way.

**Subtasks**
- [x] Fix sleeps
- [x] Fix timestamp assertions.

### PR DESCRIPTION
**Pull request by JamesMBartlett**
Summary: Removes dependence on sleeps/timing from the dynamic_bpftrace bpf test, by adding loops with timeouts to wait for records to show up.

Relevant Issues: Fixes #1245.

Type of change: /kind cleanup

Test Plan: Along with #1278, ran `bazel test --config=qemu-bpf //src/stirling/source_connectors/dynamic_bpftrace:dynamic_bpftrace_connector_bpf_test --runs_per_test=50` without any failures.

### CODE REVIEW

**Review by etep — APPROVED** [review]

File: src/stirling/source_connectors/dynamic_bpftrace/dynamic_bpftrace_connector_bpf_test.cc [hunk 1]
```diff
@@ -212,19 +219,19 @@ TEST(DynamicBPFTraceConnectorTest, BPFTraceBuiltins) {
...
     EXPECT_LE(nsecs, now_ns);
 
     int64_t elapsed = records[kElapsedIdx]->Get<types::Int64Value>(0).val;
     LOG(INFO) << absl::Substitute("elapsed: $0", elapsed);
-    // Expecting a value of close to 100 ms. Add +/- 50 ms to be generous.
+    // Expecting a value of close to 100 ms. Look for between 50 and 200 to be generous.
     constexpr int kNanosPerMilli = 1000 * 1000;
     EXPECT_GE(elapsed, 50 * kNanosPerMilli);
-    EXPECT_LE(elapsed, 150 * kNanosPerMilli);
+    EXPECT_LE(elapsed, 200 * kNanosPerMilli);
```
Comment (vihangm) [inline src/stirling/source_connectors/dynamic_bpftrace/dynamic_bpftrace_connector_bpf_test.cc:234]: This seems liable to cause flakes in the future, do we really need to have an expectation for the elapsed time?

**Review by vihangm — APPROVED** [review]

**Review by ddelnano — APPROVED** [review]
