### PR TITLE
[Kernel scoping 2/5] Add kernel version to HostInfo

### LINKED ISSUE #1582: `px/tcp_drops` pxl script broken due to missing tcp_drop kprobe
Running the `px/tcp_drops` pxl script results in the following errors:

```
$ kubectl -n pl logs vizier-pem-qrn9l

[ .. ]

stdin:26-28: WARNING: tcp_drop is not traceable (either non-existing, inlined, or marked as "notrace"); attaching to it will likely fail
I20230627 17:32:19.979256 1894345 stirling.cc:549] DynamicTraceConnector [DT_e2a6ba86-df73-4975-a291-fd8728296097] created in 5570.15 ms.
I20230627 17:32:19.979339 1894345 source_connector.cc:35] Initializing source connector: DT_e2a6ba86-df73-4975-a291-fd8728296097
cannot attach kprobe, probe entry may not exist
ERROR: Error attaching probe: 'kprobe:tcp_drop'
I20230627 17:32:20.119061 1894345 stirling.cc:566] Internal : Failed to run BPF code.
I20230627 17:32:22.009603 3168351 tracepoint_manager.cc:180] Tracepoint[e2a6ba86-df73-4975-a291-fd8728296097]::tcp_drop_tracer has transitioned PENDING_STATE -> FAILED_STATE
```

It appears that the `tcp_drop` function was removed in v5.19 kernel and that removal may have been backported to other v5.x releases. For these newer kernels there is a tracepoint available that should serve a similar purpose (`tracepoint:skb:kfree_skb`). BCC's `tcpdrop` tool uses this as a [fallback](https://github.com/iovisor/bcc/blob/6ef0f0dd2c8d315e2b6dda26e63d014a49ca9ec1/tools/tcpdrop.py#L228-L232) if the kprobe doesn't exist, so we should implement a similar fallback mechanism.

### PR DESCRIPTION
**Pull request by benkilimnik**
Summary: Adds kernel version to `HostInfo` during PEM registration. This is used to fix #1582 by scoping tracepoint deployments to nodes running certain versions of the kernel.

Related issues: #1582 #1659

Type of change: /kind feature

Test Plan: Tested all existing targets and added tests to `src/vizier/services/agent/shared/manager/registration_test.cc` and `src/vizier/services/agent/pem/pem_manager_test.cc`

### CODE REVIEW

File: src/vizier/services/agent/kelvin/kelvin_manager.h [hunk 1]
```diff
@@ -43,9 +44,11 @@ class KelvinManager : public Manager {
   KelvinManager() = delete;
   KelvinManager(sole::uuid agent_id, std::string_view pod_name, std::string_view host_ip,
                 std::string_view addr, int grpc_server_port, std::string_view nats_url,
-                std::string_view mds_url)
+                std::string_view mds_url, px::system::KernelVersion kernel_version)
+      // TODO(@benkilimnik): Kernel version may not be needed in kelvin, only in PEMManager for
+      // script selection based on HostInfo. Could use dummy value or refactor Manager class.
```
Comment (etep) [inline src/vizier/services/agent/kelvin/kelvin_manager.h:49]: Agreed that Kelvin may not need kernel version, at least for the purposes we have right now. Is it possible to remove from Kelvin (or is there some common base class where we add kernel version as an arg. making it required as an arg. here)?

Comment (benkilimnik) [reply src/vizier/services/agent/kelvin/kelvin_manager.h:49]: There is a common base class `Manager` in `vizier/services/agent/shared/manager/manager.{h,cc}` to which I've added the kernel version.

I think we could handle this in a number of ways:

1. Set a dummy value for the kernel version in `KelvinManager`. 

2. Set a flag in `Manager`
```cpp
protected:
    Manager(..., bool use_kernel_version = true);
```
```cpp
Manager::Manager(..., bool use_kernel_version) {
    if (use_kernel_version) {
        // Find and set the kernel version
    }
    // other initialization
}
```
```cpp
KelvinManager::KelvinManager(...) 
    : Manager(..., false) { // Pass false to indicate that we don't need to go find the kernel version
    // KelvinManager specific initialization
}
```

3. Refactor `Manager` such that it does not require the kernel version in its constructor, but provides a separate method to set it. Derived classes like `PEMManager` set the kernel version after construction if needed.

4. Make the kernel version optional in the base Manager class e.g. `std::optional<px::system::KernelVersion>`

Comment (ddelnano) [reply src/vizier/services/agent/kelvin/kelvin_manager.h:49]: I have another proposal for addressing this. What if we mutated the `info_` member's kernel_version field within the PEMManager's constructor body? This would allow us to remove any references of kernel version from the Manager base class and the KelvinManager.

This commit (https://github.com/pixie-io/pixie/commit/179598858ff9ee551bafcc1d36122e5b380bca2b) shows an example of what I mean. If we like that direction, I think we should also add tests to ensure that a KelvinManager and PEMManager have an `info_` member in the correct state after construction: former having kernel_version uninitialized and the latter having it set to a kernel version.

I see this as an improvement to option 3 because it ensures that a newly minted PEMManager is properly configured and reduces risk of using the API incorrectly (forgetting to call the kernel version setter).

**Review by ddelnano — COMMENTED** [review]
A few minor comments in addition to the existing discussion about how to handle the kernel version for KelvinManagers.

File: src/vizier/services/agent/shared/manager/registration.cc [hunk 2]
```diff
@@ -20,8 +20,10 @@
 #include <utility>
 #include <vector>
 
+#include "src/vizier/services/agent/shared/base/info.h"
 #include "src/vizier/services/agent/shared/manager/manager.h"
 #include "src/vizier/services/agent/shared/manager/registration.h"
+#include "src/vizier/services/metadata/metadatapb/service.grpc.pb.h"
```
[the remark this answers is not in the document]
Comment (benkilimnik) [reply src/vizier/services/agent/shared/manager/registration.cc]: This is a leftover from an old change - I've removed it in the most recent commit. Thanks for catching this.

File: src/vizier/services/agent/kelvin/kelvin_manager.h (hunk 1 above)
Comment (benkilimnik) [reply src/vizier/services/agent/kelvin/kelvin_manager.h]: That seems like a more robust solution to me.

Regarding testing, are you imagining something like this, where we check that the kernel version is initialized after construction? (I think the member function info() is protected, so we'd need a getter or friend test function). 

```cpp
class PEMManagerTest : public ::testing::Test {
    protected:
        PEMManagerTest() {
            agent_info_ = agent::Info{};
            agent_info_.agent_id = sole::uuid4();
            agent_info_.hostname = "hostname";
            agent_info_.address = "address";
            agent_info_.pod_name = "pod_name";
            agent_info_.host_ip = "host_ip";
            agent_info_.kernel_version =
                system::ParseKernelVersionString("5.15.0-106-generic").ValueOrDie();
        }

    agent::Info agent_info_;
};

TEST_F(PEMManagerTest, ConstructorTest) {
    auto manager =
      PEMManager::Create(agent_info_.agent_id, agent_info_.pod_name, agent_info_.host_ip,
                         "nats_url", agent_info_.kernel_version)
          .ConsumeValueOrDie();  // Remove the semicolon before .ConsumeValueOrDie()
    EXPECT_EQ(manager->info()->agent_id, agent_info_.agent_id);
    EXPECT_EQ(manager->info()->pod_name, agent_info_.pod_name);
    EXPECT_EQ(manager->info()->host_ip, agent_info_.host_ip);
    EXPECT_EQ(manager->info()->kernel_version, agent_info_.kernel_version);
}
```

Comment (ddelnano) [reply src/vizier/services/agent/kelvin/kelvin_manager.h]: @benkilimnik that's what I was thinking and I think making it a friend test function sounds good.

Comment (benkilimnik) [reply src/vizier/services/agent/kelvin/kelvin_manager.h]: Because of the way `PEMManager` inherits from `Manager` I have actually found it rather difficult to write a test case for this. When I instantiate the `PEMManager` I get this error

```cpp
F20230908 07:05:26.144451    12 statusor.h:148] Check failed: _s.ok() Bad Status: Internal : Failed to read file ../../services/certs/ca.crt (No such file or directory)
```

which I believe comes from `SSL::DefaultGRPCClientCreds()` in `manager.cc:103`

```cpp
Manager::Manager(sole::uuid agent_id, std::string_view pod_name, std::string_view host_ip,
                 int grpc_server_port, services::shared::agent::AgentCapabilities capabilities,
                 services::shared::agent::AgentParameters parameters, std::string_view nats_url,
                 std::string_view mds_url)
    : grpc_channel_creds_(SSL::DefaultGRPCClientCreds()),
...
```

I think a test that mocks out parts of the `Manager` constructor will require some design changes. As I see it, we could:
1. Move initialization logic out of the `Manager` constructor, so that we can avoid calling it in tests and only instantiate the object
2. Instead of directly creating instances / reading files inside the constructor, we could pass them as parameters, so that we can pass mock versions in tests.
3. Instead of inheriting from Manager, we could make `PEMManager` and `Manager` implement the same interface. Then, PEMManager can have a Manager member that it delegates to for the shared functionality. This way, we could mock out the entire Manager when testing PEMManager.

@ddelnano @etep eager to hear your thoughts on this.

Comment (benkilimnik) [reply src/vizier/services/agent/kelvin/kelvin_manager.h]: After some discussion with @ddelnano, I ended up adding a private constructor to `PEMManager` that contains a flag to skip the `Init()` of the base `Manager`. This flag is set to `false` in the public constructor and `true` in friend tests which call it.
The cert error was fixed by setting `FLAGS_disable_SSL = true;`

File: src/vizier/services/agent/kelvin/kelvin_main.cc [hunk 3]
```diff
@@ -27,6 +27,7 @@
 #include "src/common/base/base.h"
 #include "src/common/event/nats.h"
 #include "src/common/signal/signal.h"
+#include "src/common/system/kernel_version.h"
```
Comment (ddelnano) [inline src/vizier/services/agent/kelvin/kelvin_main.cc:30]: This appears to be unused.

File: src/vizier/services/agent/shared/manager/manager.cc [hunk 4]
```diff
@@ -33,6 +33,7 @@
 #include "src/common/base/base.h"
 #include "src/common/metrics/metrics.h"
 #include "src/common/perf/perf.h"
+#include "src/common/system/kernel_version.h"
```
Comment (ddelnano) [inline src/vizier/services/agent/shared/manager/manager.cc:36]: This also appears unused (compiling locally works).

**Review by ddelnano — COMMENTED** [review]
To more minor comments. Assuming @etep doesn't have any issues with the direction of how we tested this, this lgtm.

File: src/vizier/services/agent/pem/pem_manager_test.cc [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+
+DECLARE_bool(disable_SSL);
+
+namespace px {
+namespace vizier {
+namespace agent {
+
+class PEMManagerTest : public ::testing::Test {
+ protected:
+  // void TearDown() override { dispatcher_->Exit(); }
```
Comment (ddelnano) [inline src/vizier/services/agent/pem/pem_manager_test.cc:32]: @benkilimnik did you intend to have this code uncommented or can this be removed?

Comment (benkilimnik) [reply src/vizier/services/agent/pem/pem_manager_test.cc]: Just removed

File: src/vizier/services/agent/kelvin/kelvin_manager.h (hunk 1 above)
Comment (etep) [reply src/vizier/services/agent/kelvin/kelvin_manager.h]: I'd be ok with option (5) keep the version in Kelvin if it nets out to "simpler." It appears we already have a "way" to avoid going here, but is the pain worth it? I am ok with either route btw.

Comment (ddelnano) [reply src/vizier/services/agent/kelvin/kelvin_manager.h]: Despite advocating for the current direction, I do think that having the kernel version for both is likely simpler.

Sorry for causing additional change @benkilimnik, but after reconsidering (5) is probably best. If the Manager class was an area where future test coverage would helpful that might tip the scale, but as we've seen it's very difficult to exercise its code.

File: src/vizier/services/agent/pem/pem_manager.h [hunk 6]
```diff
@@ -73,7 +77,9 @@ class PEMManager : public Manager {
                                .Help("Total amount of memory on the node (includes inuse and free "
                                      "memory). Corresponds to /proc/meminfo MemTotal.")
                                .Register(GetMetricsRegistry())
-                               .Add({})) {}
+                               .Add({})) {
+    info()->kernel_version = kernel_version;
+  }
```
Comment (ddelnano) [inline src/vizier/services/agent/pem/pem_manager.h:82]: We can remove this since we went back to setting it within `Manager::Manager`.

**Review by ddelnano — APPROVED** [review]
One more minor change, but approving since we have consensus on the direction.

**Review by etep — APPROVED** [review]

**Review by JamesMBartlett — APPROVED** [review]
