### PR TITLE
[Fix CQL Sticher 3/4] Populate map of streams to frames during parsing

### LINKED ISSUE #1375: Large CQL `Result` frames (> 1MiB) cause poor CQL protocol stitching
**High Level Plan**
- [x] Prototype new stitcher implementation that accurately matches requests and responses -- prototype developed [here](https://github.com/ddelnano/pixie/tree/ddelnano/record-and-replay-with-cql-stitcher-change)
- [ ] Convert all stitching implementations to use new interface that simplifies handling protocols with streams
- [ ] Use the new interface to productionize the CQL stitcher implementation prototyped in the first bullet.

**Background**

While creating the k8ssandra demo (#680) for the recent Cassandra Town Hall, I noticed that large CQL `Result` frames cause poor protocol stitching behavior. This manifests as `Result` frames that have incorrect latency values -- requests that take tens of milliseconds to complete can be reported on the order of minutes in some cases (as seen in the reproduction below).

**To Reproduce**
1. Deploy the `px-k8ssandra` via the px cli -- `px demo deploy px-k8ssandra`. Note: this demo isn't released at this time, but will be ~1 week from the time of this writing
2. Use the `cqlsh` cli within the cassandra container to load the [following CSV file](https://github.com/pixie-io/pixie/files/11578468/petclinic_visit_by_pet.csv) into the `petclinic_visit_by_pet` table
```
# Copy CSV file containing ~8k rows into the pod
kubectl -n px-k8ssandra cp petclinic_visit_by_pet.csv  demo-dc1-default-sts-0:/tmp/

kubectl -n px-k8ssandra exec demo-dc1-default-sts-0 -it -- cqlsh -u cassandra -p cassandra -e "COPY spring_petclinic.petclinic_visit_by_pet FROM '/tmp/petclinic_visit_by_pet.csv'"
Defaulted container "cassandra" out of: cassandra, server-system-logger, server-config-init (init)
Using 3 child processes

Starting copy of spring_petclinic.petclinic_visit_by_pet with columns [pet_id, visit_id, description, visit_date].
Processed: 8511 rows; Rate:    5921 rows/s; Avg. rate:    8434 rows/s
8511 rows imported from 1 files in 0 day, 0 hour, 0 minute, and 1.009 seconds (0 skipped).
```
3. Load the `px/cql_data` script and see that the `Result` rows show traces that report seconds of latency when `curl`ing that endpoint manually shows ~100ms response times. The `px/http_data` script correctly shows the ~100ms of latency.
```
$ kubectl -n px-k8ssandra port-forward service/petclinic-backend 9966
$ time curl -s -o /dev/null localhost:9966/petclinic/api/pets

real    0m0.179s
user    0m0.000s
sys     0m0.008s

```
Screenshot 2023-05-26 at 10 23 49 AM
Screenshot 2023-05-26 at 10 26 44 AM

**Expected behavior**
These `Result` CQL frames should have latency within the bounds of the latency of the http request that triggers the queries.

In order to debug this, I updated the PEM daemonset to include `--stirling_conn_trace_pid=$cassandra_server_pid` in addition to adding more verbose logging in the CQL stitcher and logging stirling's user space buffers (code changes can be seen in https://github.com/ddelnano/pixie/commit/eb933327e94abf6bcaed9f34386033b2796a7544).

This showed that the CQL protocol parser is correctly parsing the packets the way we expect them to occur (according to Cassandra's CQL [v4 protocol spec](https://github.com/apache/cassandra/blob/4d2ee09ffabf7fb086fb9e2bd042fc946e72c3ec/doc/native_protocol_v4.spec)), however, the frame header length field seems incorrect. These `Result` frames should contain a response that is ~1 MiB in size and the frame length is much shorter than that.

After realizing that the CQL data we are parsing seems to be out of spec, I wanted to confirm this protocol parsing with another tool. I captured the CQL traffic with `tcpdump` and loaded it in Wireshark and I noticed that it is seeing the same "bogus" frame lengths that we are inferring.

I realized that the Cassandra wireshark dissector, which has the same bug or lack of functionality as our own cql parser, was contributed by the Scylladb project maintainers. Scylladb is supposed to be a drop in replacement for Cassandra and that made me consider that the Wireshark dissector is probably battle tested against whatever subset of CQL they support.

I triggered the same CQL traffic that is identified as being malformed with open source Cassandra against a Scylladb server, and I’m no longer getting malformed traffic (notice how the message length is just under 1 MB for the focused frame and that there isn’t the “Malformed packet” identified). The first picture is the Wireshark capture against open source Cassandra and the second is against Scylladb. I've also attached the packet captures for both of the screenshots below.

[Packet captures CQL.zip](https://github.com/pixie-io/pixie/files/11578614/Packet.captures.CQL.zip)

open source cassandra Wireshark

Scylladb Wireshark

### PR DESCRIPTION
**Pull request by benkilimnik**
Summary: Modifies all protocol parsers to use a map of streams to deques by default. Protocols which do not have a notion of streams are encoded as single keys in a map. This completes the CQL stitcher fix and should simplify stitching frames for protocols with streams.

The final PR in this sequence #1732 populates a map of streamIDs to deque of frames in ParseFramesLoop instead of ParseFrames. This should provide a small efficiency boost, as we won't have to loop over the frames twice.

Related issues: Closes #1375

Type of change: /kind bug

Test Plan: Updated parsing tests to use new interface. `Note`: this PR relies on changes introduced in #1689 and #1715

### CODE REVIEW

File: src/stirling/source_connectors/socket_tracer/data_stream.h [hunk 1]
```diff
@@ -254,22 +270,42 @@ class DataStream : NotCopyMoveable {
...
+        // TODO(yzhao): Benchmark with binary search and pick the faster one.
+        if (expiry_timestamp < frame_timestamp) {
+          LOG(INFO) << "Expired";
+          break;
+        }
       }
+
+      LOG(INFO) << "Distance " << std::distance(deque.begin(), iter);
+      deque.erase(deque.begin(), iter);
+      LOG(INFO) << "Size " << deque.size();
```
Comment (ddelnano) [inline src/stirling/source_connectors/socket_tracer/data_stream.h:307]: These logs statements appear to be debugging remnants.

Comment (benkilimnik) [reply src/stirling/source_connectors/socket_tracer/data_stream.h]: Removed in most recent commit

File: src/stirling/source_connectors/socket_tracer/protocols/common/event_parser.h [hunk 2]
```diff
@@ -120,28 +120,32 @@ ParseResult ParseFrames(message_type_t type, DataStreamBuffer* data_stream_buffe
...
     msg.timestamp_ns = timestamp_ns_status.ValueOr(0);
   }
   result.end_position += start_pos;
 
+  // Parse frames into map
+  for (auto& frame : new_frames) {
+    // GetStreamID returns 0 by default if not implemented in protocol.
+    TKey key = GetStreamID<TKey, TFrameType>(&frame);
+    (*frames)[key].push_back(frame);
+  }
```
Comment (ddelnano) [inline src/stirling/source_connectors/socket_tracer/protocols/common/event_parser.h:148]: Have you tried pushing the `GetStreamID` call into the `ParseFramesLoop` function? It seems like we could avoid this loop if GetStreamID could be called [here](https://github.com/pixie-io/pixie/blob/782674dec0e3a6924b7a3c3002abe13bae10fdd0/src/stirling/source_connectors/socket_tracer/protocols/common/event_parser.h#L225) as the frame is pushed into the deque.

Comment (benkilimnik) [reply src/stirling/source_connectors/socket_tracer/protocols/common/event_parser.h:148]: I originally had it in `ParseFramesLoop`, but this required changing how `ParseResult` is used to update the timestamp of each frame in lines 130-141. The code became rather verbose and required changing various test files that use `ParseFramesLoop` like `src/stirling/source_connectors/socket_tracer/protocols/{cql,dns,kafka,mysql}/parse_test.cc`, so I opted to move it into `ParseFrames` instead.

Happy to discuss further if you think it would be better to move it back into ParseFramesLoop.

File: src/stirling/e2e_tests/stirling_wrapper_size_test.cc [hunk 3]
```diff
@@ -30,7 +30,7 @@ namespace stirling {
 #ifdef __OPTIMIZE__
 constexpr uint64_t kFileSizeLimitMB = 118;
 #else
-constexpr uint64_t kFileSizeLimitMB = 295;
+constexpr uint64_t kFileSizeLimitMB = 297;
```
Comment (ddelnano) [inline src/stirling/e2e_tests/stirling_wrapper_size_test.cc:33]: I think we should raise this by 5 MiB (300) to provide more of a buffer. While your change tripped the threshold any significant code added in stirling will inch us closer to this (adding libbson, the mongo parser/stitcher, which includes templates, etc). So while your change added more code and templates instantiations, I think it's likely that the mongo work has contributed to this as well.

Comment (benkilimnik) [reply src/stirling/e2e_tests/stirling_wrapper_size_test.cc:33]: I've opened a separate PR for this #1731

File: src/stirling/source_connectors/socket_tracer/protocols/common/event_parser.h (hunk 2 above)
Comment (benkilimnik) [reply src/stirling/source_connectors/socket_tracer/protocols/common/event_parser.h]: On second thought, I think it is better to have the call to `GetStreamID` in `ParseFramesLoop`. To avoid this PR getting too large, I've moved that change to #1732

File: src/stirling/source_connectors/socket_tracer/protocols/cql/types.h [hunk 4]
```diff
@@ -103,6 +103,7 @@ struct Frame : public FrameBase {
   FrameHeader hdr;
   std::string msg;
   bool consumed = false;
+  bool discarded = false;
```
Comment (ddelnano) [inline src/stirling/source_connectors/socket_tracer/protocols/cql/types.h:106]: @benkilimnik this seems like a remnant from https://github.com/pixie-io/pixie/pull/1715

Comment (benkilimnik) [reply src/stirling/source_connectors/socket_tracer/protocols/cql/types.h]: Removed in most recent commit

**Review by ddelnano — APPROVED** [review]

File: src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc [hunk 5]
```diff
@@ -786,9 +786,11 @@ void SocketTraceConnector::TransferDataImpl(ConnectorContext* ctx) {
...
       // If there's no transfer function, then the tracker should not be holding any data.
       // http::ProtocolTraits is used as a placeholder; the frames deque is expected to be
-      // std::monotstate.
-      ECHECK(conn_tracker->send_data().Empty<protocols::http::Message>());
-      ECHECK(conn_tracker->recv_data().Empty<protocols::http::Message>());
+      // std::monostate.
+      ECHECK((conn_tracker->send_data()
+                  .Empty<protocols::http::stream_id_t, protocols::http::Message>()));
+      ECHECK((conn_tracker->recv_data()
+                  .Empty<protocols::http::stream_id_t, protocols::http::Message>()));
```
Comment (etep) [inline src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc:793]: We should probably make this a `DCHECK`.

Also, is it possible to create a type alias so that the line breaks are avoided, e.g.
```
using stream_id_t = protocols::http::stream_id_t;
using message_t = protocols::http::Message;
.Empty<stream_id_t, message_t>();
```

File: src/stirling/source_connectors/socket_tracer/data_stream.h [hunk 6]
```diff
@@ -134,10 +139,22 @@ class DataStream : NotCopyMoveable {
...
    * @return true if empty of all data.
    */
-  template <typename TFrameType>
+  template <typename TKey, typename TFrameType>
   bool Empty() const {
-    return data_buffer_.empty() && (std::holds_alternative<std::monostate>(frames_) ||
-                                    std::get<std::deque<TFrameType>>(frames_).empty());
+    bool data_buffer_empty = data_buffer_.empty();
+    bool monostate = std::holds_alternative<std::monostate>(frames_);
+    if (data_buffer_empty || monostate) {
```
[the remark this answers is not in the document]
Comment (benkilimnik) [reply src/stirling/source_connectors/socket_tracer/data_stream.h:146]: I believe the condition of the if statement depends on the runtime state of `data_buffer_` and `frames_`, so we can't use a `constexpr`.

File: src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc (hunk 5 above)
Comment (benkilimnik) [reply src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc]: Added type alias and changed to `DCHECK`

**Review by JamesMBartlett — APPROVED** [review]
