### PR TITLE
Always scroll hovered item into view in Command Palette

### LINKED ISSUE #1045: Keyboard scrolling in Command Palette can obscure results
**Describe the bug**
When using the arrow keys to look through a scrolling list of results in the Command Palette, and specifically scrolling up to an option under a heading, it will not scroll quite far enough up. This obscures the option, like so:
image

**To Reproduce**
Open the Command Palette. Enter a query like `script:`. Using the arrow keys, scroll down a couple of pages, then scroll back up the same way. When moving to an option that's above the current scroll view, it only partially scrolls into view.

**Expected behavior**
The highlighted option should scroll fully into view.

### PR DESCRIPTION
**Pull request by NickLanam**
Summary: Without this change, the browser already tries to scroll the selected option into view. However, due to `position: sticky`, there's a header that can obscure it. To account for that header, we use `scroll-margin-top` and force the browser to try again with `scrollIntoView`, which accounts for that property.
Fixes #1045

Relevant Issues: #1045

Test Plan: Open the Command Palette. Enter a query like script:. Using the arrow keys, scroll down a couple of pages, then scroll back up the same way. When moving to an option that's above the current scroll view, it should now fully scroll that option into view.

Type of change: /kind bug

Signed-off-by: Nick Lanam <nlanam@pixielabs.ai>

### CODE REVIEW

File: src/ui/src/components/command-palette/command-text-field.tsx [hunk 1]
```diff
@@ -217,8 +219,18 @@ export const CommandTextField = React.memo<CommandTextFieldProps>(({
     onChange: (_, option: CommandCompletion) => { // Takes event, option, reason, details (in case we need them)
       activateCompletion(option);
     },
-    onHighlightChange: (_, option: CommandCompletion) => {
+    onHighlightChange: (event: React.SyntheticEvent, option: CommandCompletion, reason: string) => {
       setHighlightedCompletion(option);
+      if (option && (reason === 'keyboard' || reason === 'auto')) {
+        // The event target is the text field if the reaon is keyboard, and missing if the reason is auto.
```
Comment (JamesMBartlett) [inline src/ui/src/components/command-palette/command-text-field.tsx:225]: nit: reason

File: src/ui/src/components/command-palette/command-text-field.tsx [hunk 2]
```diff
@@ -132,6 +132,11 @@ const useFieldStyles = makeStyles((theme: Theme) => createStyles({
     '&:not(:first-child)': {
       borderTop: theme.palette.border.unFocused,
     },
+    '& > $optionGroupHeading + ul > li': {
+      // Tells scrollIntoView to scroll a bit further up, so it can avoid being obscured by the sticky headers.
+      // Only applies when the header actually exists within that option's group.
+      scrollMarginTop: theme.spacing(3.125),
```
Comment (JamesMBartlett) [inline src/ui/src/components/command-palette/command-text-field.tsx:138]: This number seems a bit random to me, why 3.125?

File: src/ui/src/components/command-palette/command-text-field.tsx [hunk 3]
```diff
@@ -132,6 +132,11 @@ const useFieldStyles = makeStyles((theme: Theme) => createStyles({
     '&:not(:first-child)': {
       borderTop: theme.palette.border.unFocused,
     },
+    '& > $optionGroupHeading + ul > li': {
```
Comment (JamesMBartlett) [inline src/ui/src/components/command-palette/command-text-field.tsx:135]: This is a bit incomprehensible to me, but I don't know CSS that well so maybe its common?

File: src/ui/src/components/command-palette/command-text-field.tsx (hunk 2 above)
Comment (NickLanam) [reply src/ui/src/components/command-palette/command-text-field.tsx:138]: It matches the height of the headers defined above (computing the value would not be straightforward).

File: src/ui/src/components/command-palette/command-text-field.tsx (hunk 3 above)
Comment (NickLanam) [reply src/ui/src/components/command-palette/command-text-field.tsx:135]: Yes, this is pretty common stuff plus two Material-specific things:

- `& ...` means "prepend the rule that got us here", which is just a shorthand.
- `$anotherRule` is also a Material thing. It makes sure to copy over the generated class name correctly.
- 'foo > bar` means "a bar that is a direct child of a foo"
- `foo + bar` means "a bar that is the immediate next sibling of a foo"

All in all, this means "list items that are in groups that have headers" (as the comment implies).

**Review by JamesMBartlett — APPROVED** [review]
